services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
    - "27017:27017"
    volumes:
    - mongo-data:/data/db # to persist data
    
  # Spring Boot Application
  library-app:
    image: library-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/bookdb
    depends_on:
      - mongodb

volumes:
  mongo-data: